WHENEVER SQLERROR CONTINUE;

DROP TABLE image_data CASCADE CONSTRAINTS;
DROP TABLE action_log CASCADE CONSTRAINTS;
DROP TABLE ai_result CASCADE CONSTRAINTS;
DROP TABLE plant_growth CASCADE CONSTRAINTS;
DROP TABLE environment_data CASCADE CONSTRAINTS;
DROP TABLE growth_batch CASCADE CONSTRAINTS;
DROP TABLE field CASCADE CONSTRAINTS;
DROP TABLE refresh_tokens CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

DROP SEQUENCE image_data_seq;
DROP SEQUENCE action_log_seq;
DROP SEQUENCE ai_result_seq;
DROP SEQUENCE plant_growth_seq;
DROP SEQUENCE environment_data_seq;
DROP SEQUENCE growth_batch_seq;
DROP SEQUENCE field_seq;
DROP SEQUENCE refresh_tokens_seq;
DROP SEQUENCE users_seq;